CREATE TABLE PATIENTS(ID SERIAL PRIMARY KEY, NAME VARCHAR(50), DATE_OF_BIRTH DATE);
CREATE TABLE INVOICES(ID SERIAL PRIMARY KEY, TOTAL_AMOUNT DECIMAL, GENERATED_AT TIMESTAMP, PAYED_AT TIMESTAMP, MEDICAL_HISTORY_ID INT);
CREATE TABLE INVOICE_ITEMS(ID SERIAL PRIMARY KEY, UNIT_PRICE DECIMAL, QUANTITY INT, TOTAL_PRICE DECIMAL, INVOICE_ID INT, TREATMENT_ID INT, CONSTRAINT fk_invoices FOREIGN KEY(INVOICE_ID) REFERENCES invoices(id));
ALTER TABLE INVOICE_ITEMS ADD CONSTRAINT fk_treatments FOREIGN KEY (treatment_id) REFERENCES treatments(id);
CREATE INDEX fk_treatments ON INVOICE_ITEMS(treatment_id);
CREATE INDEX fk_invoices ON INVOICE_ITEMS(invoice_id);

CREATE TABLE  medical_histories(ID SERIAL PRIMARY KEY, admitted_at TIMESTAMP, patient_id INT, status VARCHAR(50), CONSTRAINT fk_patient FOREIGN KEY(patient_id) REFERENCES patients(id));
CREATE TABLE treatments(ID SERIAL PRIMARY KEY, type VARCHAR(70), name VARCHAR(70));
CREATE TABLE medical_appointment(ID SERIAL PRIMARY KEY, medical_history_id INT, treatment_id INT, CONSTRAINT fk_history FOREIGN KEY(medical_history_id) REFERENCES medical_histories(id));
ALTER TABLE medical_appointment ADD CONSTRAINT fk_treatment FOREIGN KEY (treatment_id) REFERENCES treatments(id);

CREATE INDEX fk_history ON medical_appointment(medical_history_id);
CREATE INDEX fk_treatment ON medical_appointment(treatment_id);
