CREATE TABLE PATIENTS(ID SERIAL PRIMARY KEY, NAME VARCHAR(50), DATE_OF_BIRTH DATE);
CREATE TABLE INVOICES(ID SERIAL PRIMARY KEY, TOTAL_AMOUNT DECIMAL, GENERATED_AT TIMESTAMP, PAYED_AT TIMESTAMP, MEDICAL_HISTORY_ID INT);
CREATE TABLE INVOICE_ITEMS(ID SERIAL PRIMARY KEY, UNIT_PRICE DECIMAL, QUANTITY INT, TOTAL_PRICE DECIMAL, INVOICE_ID INT, TREATMENT_ID INT);
