CREATE DATABASE vet_clinic;
CREATE TABLE animals (ID INT PRIMARY KEY NOT NULL, NAME TEXT NOT NULL, DATE_OF_BIRTH DATE, ESCAPE_ATTEMPTS INT, NEUTERED BOOLEAN, WEIGHT_KG REAL);

ALTER TABLE animals ADD COLUMN species VARCHAR(40);

CREATE TABLE owners (ID SERIAL PRIMARY KEY, FULL_NAME VARCHAR(50), AGE INT);
CREATE TABLE species (ID SERIAL PRIMARY KEY, NAME VARCHAR(50));
ALTER TABLE animals ADD COLUMN ID SERIAL PRIMARY KEY;
ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals ADD COLUMN species_id INT;
ALTER TABLE animals ADD CONSTRAINT fk_species_animals FOREIGN KEY (species_id) REFERENCES species (id);
ALTER TABLE animals ADD COLUMN owner_id INT;
ALTER TABLE animals ADD CONSTRAINT fk_owners_animals FOREIGN KEY (owner_id) REFERENCES owners (id);

CREATE TABLE vets (ID SERIAL PRIMARY KEY, NAME VARCHAR(50), AGE INT, DATE_OF_GRADUATION DATE);
CREATE TABLE specialization (ID SERIAL PRIMARY KEY, VETS_ID INT, SPECIES_ID INT, CONSTRAINT fk_vets FOREIGN KEY (VETS_ID) REFERENCES vets (id) ON DELETE SET NULL);
ALTER TABLE specialization ADD CONSTRAINT FK_SPECIES FOREIGN KEY (species_id) REFERENCES species(id);
CREATE TABLE visits (ID SERIAL PRIMARY KEY, DATE_OF_VIST DATE, ANIMALS_ID INT, VETS_ID INT, CONSTRAINT fk_vets FOREIGN KEY (VETS_ID) REFERENCES vets (id) ON DELETE SET NULL);
ALTER TABLE visits ADD CONSTRAINT FK_ANIMALS FOREIGN KEY (ANIMALS_ID) REFERENCES ANIMALS(ID);

ALTER TABLE specialization ADD COLUMN both_species boolean;
ALTER TABLE specialization ADD COLUMN species_name VARCHAR(50);
